MODEL:
  MODEL_TYPE: deeplabv3+
  ENCODER_NAME: resnet18
  ENCODER_WEIGHTS: imagenet
  IN_CHANNLES: 4
  NUM_CLASSES: 16
  NUM_FILTERS: 16
  IGNORE_INDEX: 0
  DICE_WEIGHT: 1.
  CONSISTENCY_WEIGHT: 1.
  CONSISTENCY_EMA_WEIGHT: 1.
  CONSISTENCY_FLIP_WEIGHT: 1.
  CONSISTENCY_FLIP_EMA_WEIGHT: 1.
  CHECKPOINT: ''


DATASET:
  ROOT_DIR: dataset
  TRAIN_BATCH: 36
  VAL_BATCH: 6
  NUM_WORKERS: 12
  VAL_SPLIT_PCT: 0.1
  PATCH_SIZE: 256
  GPU_NUM: 6
  SHUFFLE_DATASET: True


OPTIMIZER:
  TRAINING_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEP_SIZE: 6
  STEP_GAMMA: 0.1


TRAIN:
  SEED: 2022
  OUT_PATH: SemiSeg
  TRAIN_EPOCHS: 75
  VAL_STEP: 3
  LOG_STEP: 5
  CONSISTENCY: 6
  CONSISTENCY_RAMPUP: 5


METRICS:
  NUM_CLASS: 16
  IGNORE_INDEX: 0
